
#Load necessary libraries
library(randomForest)
library(ROCR)
require(Hmisc)

#Setting working Directory
setwd("C:\\Users\\alokum\\Desktop\\RF_Predictor_v2\\PRAD_Final\\GS7-TCGA")
RF_model_file="RF_model"
#datafile="testset_gcrma_tcga_all.txt"
datafile="test.tab"
clindatafile="GS7_clin.txt"

outfile="testset_RFoutput.txt"
case_pred_outfile="testset_CasePredictions.txt"
ROC_pdffile="testset_ROC.pdf"
vote_dist_pdffile="testset_vote_dist.pdf"

#Read in data (expecting a tab-delimited file with header line and rownames)
data_import=read.table(datafile, header = TRUE, na.strings = "NA", sep="\t")
clin_data_import=read.table(clindatafile, header = TRUE, na.strings = "NA", sep="\t")

#NEED TO GET CLINICAL DATA IN SAME ORDER AS GCRMA DATA
clin_data_order=order(clin_data_import[,"geo_accn"])
clindata=clin_data_import[clin_data_order,]
data_order=order(colnames(data_import)[2:length(colnames(data_import))])+1 #Order data without first three columns, then add 3 to get correct index in original file
rawdata=data_import[,c(1,data_order)] #grab first three columns, and then remaining columns in order determined above
header=colnames(rawdata)

#check the overlapping variables
#RF_predictor_names=rownames(rf_output$importance)[1:30]
RF_predictor_names=rownames(rf_output$importance)
#predictor_data=t(rawdata[,2:length(header)])
#predictor_data=predictor_data[,RF_predictor_names]
####selecting top variables from test and train data
#var=c("SPAG5","IRF5","CDC20","KIFC1","NUSAP1","KIF2C","OIP5","TOP2A","MELK","CHRM1","TNMD","FMOD","VPS36","KIAA0101","CDC25C","BGN","MKI67","COMP","CDC42EP5","NUDT7","TACC3","EPHX2","NOTCH3","CST2","GLB1L2","GEMIN4","RNF185","ZNF706","COL1A1","ORC6L")
#data=predictor_names[var,]

levels(predictor_names) <- levels(RF_predictor_names)
#check for identical data in trianing and testing dataset
identical(names(RF_predictor_names),names(predictor_names))
#Get predictor variables

predictor_data=t(rawdata[,2:length(header)])
predictor_names=as.vector((rawdata[,1])) #gene symbol
#colnames(predictor_data)=predictor_names
#colnames(predictor_data)=RF_predictor_names
colnames(predictor_data)=predictor_names

#Load RandomForests classifier from file (object "rf_output" which was saved previously)
load(file=RF_model_file)


#Run test data through forest
#=predictor_data=predictor_data[,RF_predictor_names]
RF_predictions_responses=predict(rf_output, predictor_data, type="response")
RF_predictions_votes=predict(rf_output, predictor_data, type="vote")

#Join predictions with clinical data
clindata_plusRF=cbind(clindata,RF_predictions_responses,RF_predictions_votes)

#Exclude rows with missing clinical data needed for subsequent steps
clindata_plusRF=clindata_plusRF[which(!is.na(clindata_plusRF[,"event.rfs"])),]

#write results to file
write.table(clindata_plusRF,file=case_pred_outfile, sep="\t", quote=FALSE, col.names=TRUE, row.names=FALSE)

#Determine performance statistics
confusion=table(clindata_plusRF[,c("event.rfs","RF_predictions_responses")])
rownames(confusion)=c("NoRelapse","Relapse")
sensitivity=(confusion[2,2]/(confusion[2,2]+confusion[2,1]))*100
specificity=(confusion[1,1]/(confusion[1,1]+confusion[1,2]))*100
overall_error=((confusion[1,2]+confusion[2,1])/sum(confusion))*100
overall_accuracy=((confusion[1,1]+confusion[2,2])/sum(confusion))*100
class1_error=confusion[1,2]/(confusion[1,1]+confusion[1,2])
class2_error=confusion[2,1]/(confusion[2,2]+confusion[2,1])

#Prepare stats for output to file
sens_out=paste("sensitivity=",sensitivity, sep="")
spec_out=paste("specificity=",specificity, sep="")
err_out=paste("overall error rate=",overall_error,sep="")
acc_out=paste("overall accuracy=",overall_accuracy,sep="")
misclass_1=paste(confusion[1,2], colnames(confusion)[1],"misclassified as", colnames(confusion)[2], sep=" ")
misclass_2=paste(confusion[2,1], colnames(confusion)[2],"misclassified as", colnames(confusion)[1], sep=" ")

#Prepare confusion table for writing to file
confusion_out=confusion[1:2,1:2]
confusion_out=cbind(rownames(confusion_out), confusion_out)

#Print results to file
write("confusion table", file=outfile)
write.table(confusion_out,file=outfile, sep="\t", quote=FALSE, col.names=TRUE, row.names=FALSE, append=TRUE)
write(c(sens_out,spec_out,acc_out,err_out,misclass_1,misclass_2,AUC_out), file=outfile, append=TRUE)

#Create ROC curve plot and calculate AUC
#Can use Relapse vote fractions fractions as predictive variable

#The ROC curve will be generated by stepping up through different thresholds for calling Response vs NoResponse
target=clindata_plusRF[,"event.rfs"]
target[target==1]="Relapse"
target[target==0]="NoRelapse"
relapse_scores=clindata_plusRF[,"Relapse"]


pred=prediction(relapse_scores,target)
#First calculate the AUC value
perf_AUC=performance(pred,"auc")
AUC=perf_AUC@y.values[[1]]
AUC_out=paste("AUC=",AUC,sep="")
#Then, plot the actual ROC curve
perf_ROC=performance(pred,"tpr","fpr")
pdf(file=ROC_pdffile)
plot(perf_ROC, main="ROC plot")
text(0.5,0.5,paste("AUC = ",format(AUC, digits=5, scientific=FALSE)))
dev.off()

#Print results to file
write("confusion table", file=outfile)
write.table(confusion_out,file=outfile, sep="\t", quote=FALSE, col.names=TRUE, row.names=FALSE, append=TRUE)
write(c(sens_out,spec_out,acc_out,err_out,misclass_1,misclass_2,AUC_out), file=outfile, append=TRUE)
pred=prediction(relapse_scores,target)
#First calculate the AUC value
perf_AUC=performance(pred,"auc")
AUC=perf_AUC@y.values[[1]]
AUC_out=paste("AUC=",AUC,sep="")
#Then, plot the actual ROC curve
perf_ROC=performance(pred,"tpr","fpr")
pdf(file=ROC_pdffile)
plot(perf_ROC, main="ROC plot")
text(0.5,0.5,paste("AUC = ",format(AUC, digits=5, scientific=FALSE)))
dev.off()


#######optimization
RF_predictor_names=rownames(rf_output$importance)
predictor_data=predictor_data[,RF_predictor_names]



##########publications

colSelection<- c("ATP5B","NUSAP1","XRCC2","ESPL1","CENPI","RPE65","GCGR","STMN1","LDHA","MMP11","MYH11","ZNF212","C20orf24","PKM2","CSE1L","SPAG5","NCAPH","DRAP1","GARS","CENPE","ATP2A1","CENPA","GTSE1","RFPL1","CENPF","PKMYT1","RAD54L","EYA1","FUCA1","FLNA","MYL9","ARG2","PTTG1","CEACAM1","DHFR","KIF14","CTHRC1","MT1E","UBFD1","CKMT2","TROAP","MAOA","MYLK")
featurePlot(x=rf_output[,colSelection],y = rf_output$importance,plot="pairs")


